"""initial_schema

Revision ID: 0827b0b69f86
Revises: 
Create Date: 2026-05-18 01:35:07.903448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0827b0b69f86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('keywords_json', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'slug', name='uq_animal_catalog_kind_slug')
    )
    op.create_index(op.f('ix_animal_catalog_items_id'), 'animal_catalog_items', ['id'], unique=False)
    op.create_index(op.f('ix_animal_catalog_items_kind'), 'animal_catalog_items', ['kind'], unique=False)
    op.create_index(op.f('ix_animal_catalog_items_slug'), 'animal_catalog_items', ['slug'], unique=False)
    op.create_index(op.f('ix_animal_catalog_items_sort_order'), 'animal_catalog_items', ['sort_order'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('personal_data_consent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('volunteer_competency_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_volunteer_competency_slug')
    )
    op.create_index(op.f('ix_volunteer_competency_items_id'), 'volunteer_competency_items', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_competency_items_slug'), 'volunteer_competency_items', ['slug'], unique=False)
    op.create_index(op.f('ix_volunteer_competency_items_sort_order'), 'volunteer_competency_items', ['sort_order'], unique=False)
    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_role', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('read_minutes', sa.Integer(), nullable=False),
    sa.Column('is_context_tip', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_author_user_id'), 'knowledge_articles', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_category'), 'knowledge_articles', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_created_at'), 'knowledge_articles', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_id'), 'knowledge_articles', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_is_archived'), 'knowledge_articles', ['is_archived'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_is_context_tip'), 'knowledge_articles', ['is_context_tip'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_is_published'), 'knowledge_articles', ['is_published'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_owner_role'), 'knowledge_articles', ['owner_role'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_title'), 'knowledge_articles', ['title'], unique=False)
    op.create_table('organization_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('work_territory', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('admission_rules', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_profiles_id'), 'organization_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_organization_profiles_user_id'), 'organization_profiles', ['user_id'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=160), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('specialization', sa.String(length=20), nullable=False),
    sa.Column('needs_json', sa.Text(), nullable=True),
    sa.Column('wards_count', sa.Integer(), nullable=False),
    sa.Column('adopted_yearly_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tagline', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('social_links_json', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('admission_rules', sa.Text(), nullable=True),
    sa.Column('adoption_howto', sa.Text(), nullable=True),
    sa.Column('verified_organization', sa.Boolean(), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('about_html', sa.Text(), nullable=True),
    sa.Column('gallery_json', sa.Text(), nullable=True),
    sa.Column('inn', sa.String(length=32), nullable=True),
    sa.Column('ogrn', sa.String(length=32), nullable=True),
    sa.Column('bank_account', sa.String(length=64), nullable=True),
    sa.Column('help_sections_json', sa.Text(), nullable=True),
    sa.Column('has_chat_contact', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_city'), 'organizations', ['city'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_owner_user_id'), 'organizations', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_organizations_specialization'), 'organizations', ['specialization'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_expires_at'), 'verification_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_verification_tokens_id'), 'verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_verification_tokens_purpose'), 'verification_tokens', ['purpose'], unique=False)
    op.create_index(op.f('ix_verification_tokens_token_hash'), 'verification_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_verification_tokens_user_id'), 'verification_tokens', ['user_id'], unique=False)
    op.create_table('volunteer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('availability', sa.Text(), nullable=True),
    sa.Column('location_city', sa.String(length=120), nullable=True),
    sa.Column('location_district', sa.String(length=120), nullable=True),
    sa.Column('help_format', sa.String(length=24), nullable=True),
    sa.Column('has_veterinary_education', sa.Boolean(), nullable=False),
    sa.Column('weekly_availability_json', sa.Text(), nullable=True),
    sa.Column('accepts_night_urgency', sa.Boolean(), nullable=False),
    sa.Column('travel_area_mode', sa.String(length=32), nullable=True),
    sa.Column('travel_radius_km', sa.Integer(), nullable=True),
    sa.Column('animal_types_json', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.String(length=40), nullable=True),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('completed_tasks_count', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('has_own_transport', sa.Boolean(), nullable=False),
    sa.Column('can_travel_other_area', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_profiles_experience_level'), 'volunteer_profiles', ['experience_level'], unique=False)
    op.create_index(op.f('ix_volunteer_profiles_id'), 'volunteer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_profiles_is_available'), 'volunteer_profiles', ['is_available'], unique=False)
    op.create_index(op.f('ix_volunteer_profiles_user_id'), 'volunteer_profiles', ['user_id'], unique=True)
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('species', sa.String(length=20), nullable=False),
    sa.Column('breed', sa.String(length=120), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('health_features', sa.Text(), nullable=True),
    sa.Column('treatment_required', sa.Text(), nullable=True),
    sa.Column('location_city', sa.String(length=120), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('urgent_needs_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('help_options', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_created_at'), 'animals', ['created_at'], unique=False)
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=False)
    op.create_index(op.f('ix_animals_is_urgent'), 'animals', ['is_urgent'], unique=False)
    op.create_index(op.f('ix_animals_location_city'), 'animals', ['location_city'], unique=False)
    op.create_index(op.f('ix_animals_name'), 'animals', ['name'], unique=False)
    op.create_index(op.f('ix_animals_organization_id'), 'animals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_animals_species'), 'animals', ['species'], unique=False)
    op.create_index(op.f('ix_animals_status'), 'animals', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('help_type', sa.String(length=40), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_city'), 'events', ['city'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_format'), 'events', ['format'], unique=False)
    op.create_index(op.f('ix_events_help_type'), 'events', ['help_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_is_archived'), 'events', ['is_archived'], unique=False)
    op.create_index(op.f('ix_events_is_published'), 'events', ['is_published'], unique=False)
    op.create_index(op.f('ix_events_organization_id'), 'events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_events_starts_at'), 'events', ['starts_at'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_table('org_chat_dialogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('participant_user_id', sa.Integer(), nullable=True),
    sa.Column('participant_name', sa.String(length=255), nullable=False),
    sa.Column('participant_avatar_path', sa.String(length=500), nullable=True),
    sa.Column('context_type', sa.String(length=40), nullable=True),
    sa.Column('context_entity_id', sa.Integer(), nullable=True),
    sa.Column('context_title', sa.String(length=255), nullable=True),
    sa.Column('last_message_preview', sa.String(length=500), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('unread_count_org', sa.Integer(), nullable=False),
    sa.Column('unread_count_volunteer', sa.Integer(), nullable=False),
    sa.Column('unread_count_user', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['participant_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_chat_dialogs_created_at'), 'org_chat_dialogs', ['created_at'], unique=False)
    op.create_index(op.f('ix_org_chat_dialogs_id'), 'org_chat_dialogs', ['id'], unique=False)
    op.create_index(op.f('ix_org_chat_dialogs_last_message_at'), 'org_chat_dialogs', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_org_chat_dialogs_organization_id'), 'org_chat_dialogs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_org_chat_dialogs_participant_user_id'), 'org_chat_dialogs', ['participant_user_id'], unique=False)
    op.create_table('organization_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_contacts_id'), 'organization_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_organization_contacts_organization_id'), 'organization_contacts', ['organization_id'], unique=False)
    op.create_table('organization_home_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('animal_name', sa.String(length=120), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('adopted_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_home_stories_adopted_at'), 'organization_home_stories', ['adopted_at'], unique=False)
    op.create_index(op.f('ix_organization_home_stories_animal_name'), 'organization_home_stories', ['animal_name'], unique=False)
    op.create_index(op.f('ix_organization_home_stories_id'), 'organization_home_stories', ['id'], unique=False)
    op.create_index(op.f('ix_organization_home_stories_organization_id'), 'organization_home_stories', ['organization_id'], unique=False)
    op.create_table('organization_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=600), nullable=True),
    sa.Column('detail_url', sa.String(length=2048), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_reports_id'), 'organization_reports', ['id'], unique=False)
    op.create_index(op.f('ix_organization_reports_is_published'), 'organization_reports', ['is_published'], unique=False)
    op.create_index(op.f('ix_organization_reports_organization_id'), 'organization_reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_reports_published_at'), 'organization_reports', ['published_at'], unique=False)
    op.create_index(op.f('ix_organization_reports_title'), 'organization_reports', ['title'], unique=False)
    op.create_table('organization_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('documents_url', sa.String(length=500), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_verifications_id'), 'organization_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_organization_verifications_organization_id'), 'organization_verifications', ['organization_id'], unique=True)
    op.create_table('volunteer_competency_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_profile_id', sa.Integer(), nullable=False),
    sa.Column('competency_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competency_item_id'], ['volunteer_competency_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['volunteer_profile_id'], ['volunteer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volunteer_profile_id', 'competency_item_id', name='uq_vol_prof_comp_item')
    )
    op.create_index(op.f('ix_volunteer_competency_assignments_competency_item_id'), 'volunteer_competency_assignments', ['competency_item_id'], unique=False)
    op.create_index(op.f('ix_volunteer_competency_assignments_id'), 'volunteer_competency_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_competency_assignments_volunteer_profile_id'), 'volunteer_competency_assignments', ['volunteer_profile_id'], unique=False)
    op.create_table('animal_adoption_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('applicant_name', sa.String(length=120), nullable=True),
    sa.Column('applicant_age', sa.Integer(), nullable=True),
    sa.Column('applicant_phone', sa.String(length=32), nullable=True),
    sa.Column('applicant_email', sa.String(length=320), nullable=True),
    sa.Column('housing_type', sa.String(length=20), nullable=True),
    sa.Column('housing_ownership', sa.String(length=20), nullable=True),
    sa.Column('residents_consent', sa.Boolean(), nullable=True),
    sa.Column('has_children', sa.Boolean(), nullable=True),
    sa.Column('has_allergy', sa.Boolean(), nullable=True),
    sa.Column('had_pets_before', sa.Boolean(), nullable=True),
    sa.Column('has_pets_now', sa.Boolean(), nullable=True),
    sa.Column('pet_experience', sa.Text(), nullable=True),
    sa.Column('why_now', sa.Text(), nullable=True),
    sa.Column('who_looking_for', sa.Text(), nullable=True),
    sa.Column('ready_for_vet_costs', sa.Boolean(), nullable=True),
    sa.Column('feeding_plan', sa.String(length=500), nullable=True),
    sa.Column('ready_for_vaccination', sa.Boolean(), nullable=True),
    sa.Column('time_to_devote', sa.String(length=500), nullable=True),
    sa.Column('vacation_care', sa.String(length=500), nullable=True),
    sa.Column('return_plan', sa.Text(), nullable=True),
    sa.Column('ready_to_sign_contract', sa.Boolean(), nullable=True),
    sa.Column('ready_to_show_conditions', sa.Boolean(), nullable=True),
    sa.Column('ready_to_keep_in_touch', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'animal_id', name='uq_adoption_application_user_animal')
    )
    op.create_index(op.f('ix_animal_adoption_applications_animal_id'), 'animal_adoption_applications', ['animal_id'], unique=False)
    op.create_index(op.f('ix_animal_adoption_applications_created_at'), 'animal_adoption_applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_animal_adoption_applications_id'), 'animal_adoption_applications', ['id'], unique=False)
    op.create_index(op.f('ix_animal_adoption_applications_status'), 'animal_adoption_applications', ['status'], unique=False)
    op.create_index(op.f('ix_animal_adoption_applications_user_id'), 'animal_adoption_applications', ['user_id'], unique=False)
    op.create_table('animal_catalog_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['animal_catalog_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id', 'catalog_item_id', name='uq_animal_cat_assign_animal_item')
    )
    op.create_index(op.f('ix_animal_catalog_assignments_animal_id'), 'animal_catalog_assignments', ['animal_id'], unique=False)
    op.create_index(op.f('ix_animal_catalog_assignments_catalog_item_id'), 'animal_catalog_assignments', ['catalog_item_id'], unique=False)
    op.create_index(op.f('ix_animal_catalog_assignments_id'), 'animal_catalog_assignments', ['id'], unique=False)
    op.create_table('animal_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_photos_animal_id'), 'animal_photos', ['animal_id'], unique=False)
    op.create_index(op.f('ix_animal_photos_created_at'), 'animal_photos', ['created_at'], unique=False)
    op.create_index(op.f('ix_animal_photos_id'), 'animal_photos', ['id'], unique=False)
    op.create_table('help_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('help_type', sa.String(length=40), nullable=False),
    sa.Column('urgency_level', sa.String(length=32), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('volunteer_needed', sa.Boolean(), nullable=False),
    sa.Column('volunteer_requirements', sa.Text(), nullable=True),
    sa.Column('volunteer_competencies_json', sa.Text(), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('deadline_note', sa.String(length=255), nullable=True),
    sa.Column('media_path', sa.String(length=500), nullable=True),
    sa.Column('payment_bank_account', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_help_requests_animal_id'), 'help_requests', ['animal_id'], unique=False)
    op.create_index(op.f('ix_help_requests_city'), 'help_requests', ['city'], unique=False)
    op.create_index(op.f('ix_help_requests_created_at'), 'help_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_help_requests_deadline_at'), 'help_requests', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_help_requests_help_type'), 'help_requests', ['help_type'], unique=False)
    op.create_index(op.f('ix_help_requests_id'), 'help_requests', ['id'], unique=False)
    op.create_index(op.f('ix_help_requests_is_archived'), 'help_requests', ['is_archived'], unique=False)
    op.create_index(op.f('ix_help_requests_is_published'), 'help_requests', ['is_published'], unique=False)
    op.create_index(op.f('ix_help_requests_is_urgent'), 'help_requests', ['is_urgent'], unique=False)
    op.create_index(op.f('ix_help_requests_organization_id'), 'help_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_help_requests_status'), 'help_requests', ['status'], unique=False)
    op.create_index(op.f('ix_help_requests_title'), 'help_requests', ['title'], unique=False)
    op.create_index(op.f('ix_help_requests_volunteer_needed'), 'help_requests', ['volunteer_needed'], unique=False)
    op.create_table('org_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialog_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('sender_role', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_by_org_at', sa.DateTime(), nullable=True),
    sa.Column('read_by_volunteer_at', sa.DateTime(), nullable=True),
    sa.Column('read_by_user_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dialog_id'], ['org_chat_dialogs.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_chat_messages_created_at'), 'org_chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_org_chat_messages_dialog_id'), 'org_chat_messages', ['dialog_id'], unique=False)
    op.create_index(op.f('ix_org_chat_messages_id'), 'org_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_org_chat_messages_read_by_org_at'), 'org_chat_messages', ['read_by_org_at'], unique=False)
    op.create_index(op.f('ix_org_chat_messages_read_by_user_at'), 'org_chat_messages', ['read_by_user_at'], unique=False)
    op.create_index(op.f('ix_org_chat_messages_read_by_volunteer_at'), 'org_chat_messages', ['read_by_volunteer_at'], unique=False)
    op.create_index(op.f('ix_org_chat_messages_sender_role'), 'org_chat_messages', ['sender_role'], unique=False)
    op.create_index(op.f('ix_org_chat_messages_sender_user_id'), 'org_chat_messages', ['sender_user_id'], unique=False)
    op.create_table('volunteer_help_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_user_id', sa.Integer(), nullable=False),
    sa.Column('help_request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_requests.id'], ),
    sa.ForeignKeyConstraint(['volunteer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volunteer_user_id', 'help_request_id', name='uq_vol_help_resp_user_request')
    )
    op.create_index(op.f('ix_volunteer_help_responses_created_at'), 'volunteer_help_responses', ['created_at'], unique=False)
    op.create_index(op.f('ix_volunteer_help_responses_help_request_id'), 'volunteer_help_responses', ['help_request_id'], unique=False)
    op.create_index(op.f('ix_volunteer_help_responses_id'), 'volunteer_help_responses', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_help_responses_status'), 'volunteer_help_responses', ['status'], unique=False)
    op.create_index(op.f('ix_volunteer_help_responses_volunteer_user_id'), 'volunteer_help_responses', ['volunteer_user_id'], unique=False)
    op.create_table('volunteer_help_response_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_help_response_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('org_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('org_rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['volunteer_help_response_id'], ['volunteer_help_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_help_response_reports_id'), 'volunteer_help_response_reports', ['id'], unique=False)
    op.create_index(op.f('ix_volunteer_help_response_reports_submitted_at'), 'volunteer_help_response_reports', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_volunteer_help_response_reports_volunteer_help_response_id'), 'volunteer_help_response_reports', ['volunteer_help_response_id'], unique=True)
    op.create_index('ix_help_requests_public_urgent', 'help_requests', ['is_published', 'is_archived', 'is_urgent', 'deadline_at'], unique=False)
    op.create_index('ix_knowledge_articles_public_list', 'knowledge_articles', ['is_published', 'is_archived', 'created_at'], unique=False)
    op.create_index('ix_events_public_list', 'events', ['is_published', 'is_archived', 'starts_at'], unique=False)
    op.create_index('ix_organizations_geo', 'organizations', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_events_geo', 'events', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_volunteer_profiles_geo', 'volunteer_profiles', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_org_chat_dialogs_org_participant', 'org_chat_dialogs', ['organization_id', 'participant_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_org_chat_dialogs_org_participant', table_name='org_chat_dialogs')
    op.drop_index('ix_volunteer_profiles_geo', table_name='volunteer_profiles')
    op.drop_index('ix_events_geo', table_name='events')
    op.drop_index('ix_organizations_geo', table_name='organizations')
    op.drop_index('ix_events_public_list', table_name='events')
    op.drop_index('ix_knowledge_articles_public_list', table_name='knowledge_articles')
    op.drop_index('ix_help_requests_public_urgent', table_name='help_requests')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volunteer_help_response_reports_volunteer_help_response_id'), table_name='volunteer_help_response_reports')
    op.drop_index(op.f('ix_volunteer_help_response_reports_submitted_at'), table_name='volunteer_help_response_reports')
    op.drop_index(op.f('ix_volunteer_help_response_reports_id'), table_name='volunteer_help_response_reports')
    op.drop_table('volunteer_help_response_reports')
    op.drop_index(op.f('ix_volunteer_help_responses_volunteer_user_id'), table_name='volunteer_help_responses')
    op.drop_index(op.f('ix_volunteer_help_responses_status'), table_name='volunteer_help_responses')
    op.drop_index(op.f('ix_volunteer_help_responses_id'), table_name='volunteer_help_responses')
    op.drop_index(op.f('ix_volunteer_help_responses_help_request_id'), table_name='volunteer_help_responses')
    op.drop_index(op.f('ix_volunteer_help_responses_created_at'), table_name='volunteer_help_responses')
    op.drop_table('volunteer_help_responses')
    op.drop_index(op.f('ix_org_chat_messages_sender_user_id'), table_name='org_chat_messages')
    op.drop_index(op.f('ix_org_chat_messages_sender_role'), table_name='org_chat_messages')
    op.drop_index(op.f('ix_org_chat_messages_read_by_volunteer_at'), table_name='org_chat_messages')
    op.drop_index(op.f('ix_org_chat_messages_read_by_user_at'), table_name='org_chat_messages')
    op.drop_index(op.f('ix_org_chat_messages_read_by_org_at'), table_name='org_chat_messages')
    op.drop_index(op.f('ix_org_chat_messages_id'), table_name='org_chat_messages')
    op.drop_index(op.f('ix_org_chat_messages_dialog_id'), table_name='org_chat_messages')
    op.drop_index(op.f('ix_org_chat_messages_created_at'), table_name='org_chat_messages')
    op.drop_table('org_chat_messages')
    op.drop_index(op.f('ix_help_requests_volunteer_needed'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_title'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_status'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_organization_id'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_is_urgent'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_is_published'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_is_archived'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_id'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_help_type'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_deadline_at'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_created_at'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_city'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_animal_id'), table_name='help_requests')
    op.drop_table('help_requests')
    op.drop_index(op.f('ix_animal_photos_id'), table_name='animal_photos')
    op.drop_index(op.f('ix_animal_photos_created_at'), table_name='animal_photos')
    op.drop_index(op.f('ix_animal_photos_animal_id'), table_name='animal_photos')
    op.drop_table('animal_photos')
    op.drop_index(op.f('ix_animal_catalog_assignments_id'), table_name='animal_catalog_assignments')
    op.drop_index(op.f('ix_animal_catalog_assignments_catalog_item_id'), table_name='animal_catalog_assignments')
    op.drop_index(op.f('ix_animal_catalog_assignments_animal_id'), table_name='animal_catalog_assignments')
    op.drop_table('animal_catalog_assignments')
    op.drop_index(op.f('ix_animal_adoption_applications_user_id'), table_name='animal_adoption_applications')
    op.drop_index(op.f('ix_animal_adoption_applications_status'), table_name='animal_adoption_applications')
    op.drop_index(op.f('ix_animal_adoption_applications_id'), table_name='animal_adoption_applications')
    op.drop_index(op.f('ix_animal_adoption_applications_created_at'), table_name='animal_adoption_applications')
    op.drop_index(op.f('ix_animal_adoption_applications_animal_id'), table_name='animal_adoption_applications')
    op.drop_table('animal_adoption_applications')
    op.drop_index(op.f('ix_volunteer_competency_assignments_volunteer_profile_id'), table_name='volunteer_competency_assignments')
    op.drop_index(op.f('ix_volunteer_competency_assignments_id'), table_name='volunteer_competency_assignments')
    op.drop_index(op.f('ix_volunteer_competency_assignments_competency_item_id'), table_name='volunteer_competency_assignments')
    op.drop_table('volunteer_competency_assignments')
    op.drop_index(op.f('ix_organization_verifications_organization_id'), table_name='organization_verifications')
    op.drop_index(op.f('ix_organization_verifications_id'), table_name='organization_verifications')
    op.drop_table('organization_verifications')
    op.drop_index(op.f('ix_organization_reports_title'), table_name='organization_reports')
    op.drop_index(op.f('ix_organization_reports_published_at'), table_name='organization_reports')
    op.drop_index(op.f('ix_organization_reports_organization_id'), table_name='organization_reports')
    op.drop_index(op.f('ix_organization_reports_is_published'), table_name='organization_reports')
    op.drop_index(op.f('ix_organization_reports_id'), table_name='organization_reports')
    op.drop_table('organization_reports')
    op.drop_index(op.f('ix_organization_home_stories_organization_id'), table_name='organization_home_stories')
    op.drop_index(op.f('ix_organization_home_stories_id'), table_name='organization_home_stories')
    op.drop_index(op.f('ix_organization_home_stories_animal_name'), table_name='organization_home_stories')
    op.drop_index(op.f('ix_organization_home_stories_adopted_at'), table_name='organization_home_stories')
    op.drop_table('organization_home_stories')
    op.drop_index(op.f('ix_organization_contacts_organization_id'), table_name='organization_contacts')
    op.drop_index(op.f('ix_organization_contacts_id'), table_name='organization_contacts')
    op.drop_table('organization_contacts')
    op.drop_index(op.f('ix_org_chat_dialogs_participant_user_id'), table_name='org_chat_dialogs')
    op.drop_index(op.f('ix_org_chat_dialogs_organization_id'), table_name='org_chat_dialogs')
    op.drop_index(op.f('ix_org_chat_dialogs_last_message_at'), table_name='org_chat_dialogs')
    op.drop_index(op.f('ix_org_chat_dialogs_id'), table_name='org_chat_dialogs')
    op.drop_index(op.f('ix_org_chat_dialogs_created_at'), table_name='org_chat_dialogs')
    op.drop_table('org_chat_dialogs')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_starts_at'), table_name='events')
    op.drop_index(op.f('ix_events_organization_id'), table_name='events')
    op.drop_index(op.f('ix_events_is_published'), table_name='events')
    op.drop_index(op.f('ix_events_is_archived'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_help_type'), table_name='events')
    op.drop_index(op.f('ix_events_format'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_events_city'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_animals_status'), table_name='animals')
    op.drop_index(op.f('ix_animals_species'), table_name='animals')
    op.drop_index(op.f('ix_animals_organization_id'), table_name='animals')
    op.drop_index(op.f('ix_animals_name'), table_name='animals')
    op.drop_index(op.f('ix_animals_location_city'), table_name='animals')
    op.drop_index(op.f('ix_animals_is_urgent'), table_name='animals')
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.drop_index(op.f('ix_animals_created_at'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_volunteer_profiles_user_id'), table_name='volunteer_profiles')
    op.drop_index(op.f('ix_volunteer_profiles_is_available'), table_name='volunteer_profiles')
    op.drop_index(op.f('ix_volunteer_profiles_id'), table_name='volunteer_profiles')
    op.drop_index(op.f('ix_volunteer_profiles_experience_level'), table_name='volunteer_profiles')
    op.drop_table('volunteer_profiles')
    op.drop_index(op.f('ix_verification_tokens_user_id'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_token_hash'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_purpose'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_id'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_expires_at'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_organizations_specialization'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_owner_user_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_city'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_organization_profiles_user_id'), table_name='organization_profiles')
    op.drop_index(op.f('ix_organization_profiles_id'), table_name='organization_profiles')
    op.drop_table('organization_profiles')
    op.drop_index(op.f('ix_knowledge_articles_title'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_owner_role'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_is_published'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_is_context_tip'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_is_archived'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_id'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_created_at'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_category'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_author_user_id'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index(op.f('ix_volunteer_competency_items_sort_order'), table_name='volunteer_competency_items')
    op.drop_index(op.f('ix_volunteer_competency_items_slug'), table_name='volunteer_competency_items')
    op.drop_index(op.f('ix_volunteer_competency_items_id'), table_name='volunteer_competency_items')
    op.drop_table('volunteer_competency_items')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_animal_catalog_items_sort_order'), table_name='animal_catalog_items')
    op.drop_index(op.f('ix_animal_catalog_items_slug'), table_name='animal_catalog_items')
    op.drop_index(op.f('ix_animal_catalog_items_kind'), table_name='animal_catalog_items')
    op.drop_index(op.f('ix_animal_catalog_items_id'), table_name='animal_catalog_items')
    op.drop_table('animal_catalog_items')
    # ### end Alembic commands ###
